# Generated by Django 3.2.9 on 2021-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211204_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='countrycode',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(default=False, max_length=20),
        ),
    ]
