# Generated by Django 3.2.9 on 2021-12-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211207_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verify',
        ),
    ]
